// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: guiMessage_test.proto

#include "guiMessage_test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_guiMessage_5ftest_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_guiMessage_5ftest_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Color;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_guiMessage_5ftest_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LayoutNode;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_guiMessage_5ftest_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_NumericValue;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_guiMessage_5ftest_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_Widget;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_guiMessage_5ftest_2eproto ::google::protobuf::internal::SCCInfo<2> scc_info_ContentNode;
}  // namespace protobuf_guiMessage_5ftest_2eproto
namespace guiMessage {
class LayoutNodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LayoutNode>
      _instance;
} _LayoutNode_default_instance_;
class ColorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Color>
      _instance;
} _Color_default_instance_;
class NumericValueDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NumericValue>
      _instance;
} _NumericValue_default_instance_;
class WidgetDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Widget>
      _instance;
} _Widget_default_instance_;
class ContentNodeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ContentNode>
      _instance;
  const ::guiMessage::NumericValue* numericvalue_;
  const ::guiMessage::Widget* widget_;
} _ContentNode_default_instance_;
class GuiDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Gui>
      _instance;
} _Gui_default_instance_;
}  // namespace guiMessage
namespace protobuf_guiMessage_5ftest_2eproto {
static void InitDefaultsLayoutNode() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_LayoutNode_default_instance_;
    new (ptr) ::guiMessage::LayoutNode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::LayoutNode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LayoutNode =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLayoutNode}, {}};

static void InitDefaultsColor() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_Color_default_instance_;
    new (ptr) ::guiMessage::Color();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::Color::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Color =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsColor}, {}};

static void InitDefaultsNumericValue() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_NumericValue_default_instance_;
    new (ptr) ::guiMessage::NumericValue();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::NumericValue::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_NumericValue =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsNumericValue}, {
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Color.base,}};

static void InitDefaultsWidget() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_Widget_default_instance_;
    new (ptr) ::guiMessage::Widget();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::Widget::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Widget =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsWidget}, {
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Color.base,}};

static void InitDefaultsContentNode() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_ContentNode_default_instance_;
    new (ptr) ::guiMessage::ContentNode();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::ContentNode::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ContentNode =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsContentNode}, {
      &protobuf_guiMessage_5ftest_2eproto::scc_info_NumericValue.base,
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Widget.base,}};

static void InitDefaultsGui() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::guiMessage::_Gui_default_instance_;
    new (ptr) ::guiMessage::Gui();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::guiMessage::Gui::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_Gui =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsGui}, {
      &protobuf_guiMessage_5ftest_2eproto::scc_info_LayoutNode.base,
      &protobuf_guiMessage_5ftest_2eproto::scc_info_ContentNode.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_LayoutNode.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Color.base);
  ::google::protobuf::internal::InitSCC(&scc_info_NumericValue.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Widget.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ContentNode.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Gui.base);
}

::google::protobuf::Metadata file_level_metadata[6];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::LayoutNode, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::LayoutNode, parent_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::LayoutNode, nodeid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::LayoutNode, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::LayoutNode, weight_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Color, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Color, r_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Color, g_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Color, b_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::NumericValue, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::NumericValue, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::NumericValue, value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::NumericValue, label_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Widget, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Widget, color_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::ContentNode, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::ContentNode, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::ContentNode, layoutnodeid_),
  offsetof(::guiMessage::ContentNodeDefaultTypeInternal, numericvalue_),
  offsetof(::guiMessage::ContentNodeDefaultTypeInternal, widget_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::ContentNode, Content_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Gui, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Gui, layoutnodes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::guiMessage::Gui, contentnodes_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::guiMessage::LayoutNode)},
  { 9, -1, sizeof(::guiMessage::Color)},
  { 17, -1, sizeof(::guiMessage::NumericValue)},
  { 25, -1, sizeof(::guiMessage::Widget)},
  { 31, -1, sizeof(::guiMessage::ContentNode)},
  { 40, -1, sizeof(::guiMessage::Gui)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_LayoutNode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_Color_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_NumericValue_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_Widget_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_ContentNode_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::guiMessage::_Gui_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "guiMessage_test.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\025guiMessage_test.proto\022\nguiMessage\032\023bre"
      "wblox_test.proto\032\021nanopb_test.proto\"q\n\nL"
      "ayoutNode\022\025\n\006parent\030\001 \001(\rB\005\222\?\0028\010\022\025\n\006node"
      "Id\030\002 \001(\rB\005\222\?\0028\010\022\036\n\004type\030\003 \001(\0162\020.guiMessa"
      "ge.Type\022\025\n\006weight\030\004 \001(\rB\005\222\?\0028\020\"=\n\005Color\022"
      "\020\n\001r\030\001 \001(\rB\005\222\?\0028\010\022\020\n\001g\030\002 \001(\rB\005\222\?\0028\010\022\020\n\001b"
      "\030\003 \001(\rB\005\222\?\0028\010\"\\\n\014NumericValue\022 \n\005color\030\001"
      " \001(\0132\021.guiMessage.Color\022\024\n\005value\030\002 \001(\rB\005"
      "\222\?\0028\010\022\024\n\005label\030\003 \001(\tB\005\222\?\002p(\"*\n\006Widget\022 \n"
      "\005color\030\001 \001(\0132\021.guiMessage.Color\"\206\001\n\013Cont"
      "entNode\022\024\n\014layoutNodeId\030\001 \001(\r\0220\n\014numeric"
      "Value\030\002 \001(\0132\030.guiMessage.NumericValueH\000\022"
      "$\n\006widget\030\003 \001(\0132\022.guiMessage.WidgetH\000B\t\n"
      "\007Content\"a\n\003Gui\022+\n\013layoutNodes\030\001 \003(\0132\026.g"
      "uiMessage.LayoutNode\022-\n\014contentNodes\030\002 \003"
      "(\0132\027.guiMessage.ContentNode*(\n\004Type\022\007\n\003R"
      "ow\020\000\022\n\n\006Column\020\001\022\013\n\007Content\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 677);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "guiMessage_test.proto", &protobuf_RegisterTypes);
  ::protobuf_brewblox_5ftest_2eproto::AddDescriptors();
  ::protobuf_nanopb_5ftest_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_guiMessage_5ftest_2eproto
namespace guiMessage {
const ::google::protobuf::EnumDescriptor* Type_descriptor() {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_guiMessage_5ftest_2eproto::file_level_enum_descriptors[0];
}
bool Type_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void LayoutNode::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LayoutNode::kParentFieldNumber;
const int LayoutNode::kNodeIdFieldNumber;
const int LayoutNode::kTypeFieldNumber;
const int LayoutNode::kWeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LayoutNode::LayoutNode()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_LayoutNode.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.LayoutNode)
}
LayoutNode::LayoutNode(const LayoutNode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&parent_, &from.parent_,
    static_cast<size_t>(reinterpret_cast<char*>(&weight_) -
    reinterpret_cast<char*>(&parent_)) + sizeof(weight_));
  // @@protoc_insertion_point(copy_constructor:guiMessage.LayoutNode)
}

void LayoutNode::SharedCtor() {
  ::memset(&parent_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weight_) -
      reinterpret_cast<char*>(&parent_)) + sizeof(weight_));
}

LayoutNode::~LayoutNode() {
  // @@protoc_insertion_point(destructor:guiMessage.LayoutNode)
  SharedDtor();
}

void LayoutNode::SharedDtor() {
}

void LayoutNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LayoutNode::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LayoutNode& LayoutNode::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_LayoutNode.base);
  return *internal_default_instance();
}


void LayoutNode::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.LayoutNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&parent_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weight_) -
      reinterpret_cast<char*>(&parent_)) + sizeof(weight_));
  _internal_metadata_.Clear();
}

bool LayoutNode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.LayoutNode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 parent = 1 [(.nanopb) = {
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &parent_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 nodeId = 2 [(.nanopb) = {
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &nodeid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .guiMessage.Type type = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::guiMessage::Type >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 weight = 4 [(.nanopb) = {
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.LayoutNode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.LayoutNode)
  return false;
#undef DO_
}

void LayoutNode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.LayoutNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 parent = 1 [(.nanopb) = {
  if (this->parent() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->parent(), output);
  }

  // uint32 nodeId = 2 [(.nanopb) = {
  if (this->nodeid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->nodeid(), output);
  }

  // .guiMessage.Type type = 3;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->type(), output);
  }

  // uint32 weight = 4 [(.nanopb) = {
  if (this->weight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->weight(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.LayoutNode)
}

::google::protobuf::uint8* LayoutNode::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.LayoutNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 parent = 1 [(.nanopb) = {
  if (this->parent() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->parent(), target);
  }

  // uint32 nodeId = 2 [(.nanopb) = {
  if (this->nodeid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->nodeid(), target);
  }

  // .guiMessage.Type type = 3;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      3, this->type(), target);
  }

  // uint32 weight = 4 [(.nanopb) = {
  if (this->weight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->weight(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.LayoutNode)
  return target;
}

size_t LayoutNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.LayoutNode)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 parent = 1 [(.nanopb) = {
  if (this->parent() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->parent());
  }

  // uint32 nodeId = 2 [(.nanopb) = {
  if (this->nodeid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->nodeid());
  }

  // .guiMessage.Type type = 3;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // uint32 weight = 4 [(.nanopb) = {
  if (this->weight() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->weight());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LayoutNode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.LayoutNode)
  GOOGLE_DCHECK_NE(&from, this);
  const LayoutNode* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LayoutNode>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.LayoutNode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.LayoutNode)
    MergeFrom(*source);
  }
}

void LayoutNode::MergeFrom(const LayoutNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.LayoutNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.parent() != 0) {
    set_parent(from.parent());
  }
  if (from.nodeid() != 0) {
    set_nodeid(from.nodeid());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.weight() != 0) {
    set_weight(from.weight());
  }
}

void LayoutNode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.LayoutNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LayoutNode::CopyFrom(const LayoutNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.LayoutNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LayoutNode::IsInitialized() const {
  return true;
}

void LayoutNode::Swap(LayoutNode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LayoutNode::InternalSwap(LayoutNode* other) {
  using std::swap;
  swap(parent_, other->parent_);
  swap(nodeid_, other->nodeid_);
  swap(type_, other->type_);
  swap(weight_, other->weight_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LayoutNode::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Color::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Color::kRFieldNumber;
const int Color::kGFieldNumber;
const int Color::kBFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Color::Color()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Color.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.Color)
}
Color::Color(const Color& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&r_, &from.r_,
    static_cast<size_t>(reinterpret_cast<char*>(&b_) -
    reinterpret_cast<char*>(&r_)) + sizeof(b_));
  // @@protoc_insertion_point(copy_constructor:guiMessage.Color)
}

void Color::SharedCtor() {
  ::memset(&r_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&b_) -
      reinterpret_cast<char*>(&r_)) + sizeof(b_));
}

Color::~Color() {
  // @@protoc_insertion_point(destructor:guiMessage.Color)
  SharedDtor();
}

void Color::SharedDtor() {
}

void Color::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Color::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Color& Color::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_Color.base);
  return *internal_default_instance();
}


void Color::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.Color)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&r_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&b_) -
      reinterpret_cast<char*>(&r_)) + sizeof(b_));
  _internal_metadata_.Clear();
}

bool Color::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.Color)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 r = 1 [(.nanopb) = {
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &r_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 g = 2 [(.nanopb) = {
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &g_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 b = 3 [(.nanopb) = {
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &b_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.Color)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.Color)
  return false;
#undef DO_
}

void Color::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.Color)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 r = 1 [(.nanopb) = {
  if (this->r() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->r(), output);
  }

  // uint32 g = 2 [(.nanopb) = {
  if (this->g() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->g(), output);
  }

  // uint32 b = 3 [(.nanopb) = {
  if (this->b() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->b(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.Color)
}

::google::protobuf::uint8* Color::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.Color)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 r = 1 [(.nanopb) = {
  if (this->r() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->r(), target);
  }

  // uint32 g = 2 [(.nanopb) = {
  if (this->g() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->g(), target);
  }

  // uint32 b = 3 [(.nanopb) = {
  if (this->b() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->b(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.Color)
  return target;
}

size_t Color::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.Color)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 r = 1 [(.nanopb) = {
  if (this->r() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->r());
  }

  // uint32 g = 2 [(.nanopb) = {
  if (this->g() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->g());
  }

  // uint32 b = 3 [(.nanopb) = {
  if (this->b() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->b());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Color::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.Color)
  GOOGLE_DCHECK_NE(&from, this);
  const Color* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Color>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.Color)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.Color)
    MergeFrom(*source);
  }
}

void Color::MergeFrom(const Color& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.Color)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.r() != 0) {
    set_r(from.r());
  }
  if (from.g() != 0) {
    set_g(from.g());
  }
  if (from.b() != 0) {
    set_b(from.b());
  }
}

void Color::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.Color)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Color::CopyFrom(const Color& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.Color)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Color::IsInitialized() const {
  return true;
}

void Color::Swap(Color* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Color::InternalSwap(Color* other) {
  using std::swap;
  swap(r_, other->r_);
  swap(g_, other->g_);
  swap(b_, other->b_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Color::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void NumericValue::InitAsDefaultInstance() {
  ::guiMessage::_NumericValue_default_instance_._instance.get_mutable()->color_ = const_cast< ::guiMessage::Color*>(
      ::guiMessage::Color::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NumericValue::kColorFieldNumber;
const int NumericValue::kValueFieldNumber;
const int NumericValue::kLabelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NumericValue::NumericValue()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_NumericValue.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.NumericValue)
}
NumericValue::NumericValue(const NumericValue& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.label().size() > 0) {
    label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
  }
  if (from.has_color()) {
    color_ = new ::guiMessage::Color(*from.color_);
  } else {
    color_ = NULL;
  }
  value_ = from.value_;
  // @@protoc_insertion_point(copy_constructor:guiMessage.NumericValue)
}

void NumericValue::SharedCtor() {
  label_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&color_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value_) -
      reinterpret_cast<char*>(&color_)) + sizeof(value_));
}

NumericValue::~NumericValue() {
  // @@protoc_insertion_point(destructor:guiMessage.NumericValue)
  SharedDtor();
}

void NumericValue::SharedDtor() {
  label_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete color_;
}

void NumericValue::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NumericValue::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NumericValue& NumericValue::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_NumericValue.base);
  return *internal_default_instance();
}


void NumericValue::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.NumericValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  label_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && color_ != NULL) {
    delete color_;
  }
  color_ = NULL;
  value_ = 0u;
  _internal_metadata_.Clear();
}

bool NumericValue::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.NumericValue)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .guiMessage.Color color = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 value = 2 [(.nanopb) = {
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &value_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string label = 3 [(.nanopb) = {
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_label()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->label().data(), static_cast<int>(this->label().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "guiMessage.NumericValue.label"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.NumericValue)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.NumericValue)
  return false;
#undef DO_
}

void NumericValue::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.NumericValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_color(), output);
  }

  // uint32 value = 2 [(.nanopb) = {
  if (this->value() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->value(), output);
  }

  // string label = 3 [(.nanopb) = {
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), static_cast<int>(this->label().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "guiMessage.NumericValue.label");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->label(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.NumericValue)
}

::google::protobuf::uint8* NumericValue::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.NumericValue)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_color(), deterministic, target);
  }

  // uint32 value = 2 [(.nanopb) = {
  if (this->value() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->value(), target);
  }

  // string label = 3 [(.nanopb) = {
  if (this->label().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->label().data(), static_cast<int>(this->label().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "guiMessage.NumericValue.label");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->label(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.NumericValue)
  return target;
}

size_t NumericValue::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.NumericValue)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string label = 3 [(.nanopb) = {
  if (this->label().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->label());
  }

  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *color_);
  }

  // uint32 value = 2 [(.nanopb) = {
  if (this->value() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->value());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NumericValue::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.NumericValue)
  GOOGLE_DCHECK_NE(&from, this);
  const NumericValue* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NumericValue>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.NumericValue)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.NumericValue)
    MergeFrom(*source);
  }
}

void NumericValue::MergeFrom(const NumericValue& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.NumericValue)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.label().size() > 0) {

    label_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.label_);
  }
  if (from.has_color()) {
    mutable_color()->::guiMessage::Color::MergeFrom(from.color());
  }
  if (from.value() != 0) {
    set_value(from.value());
  }
}

void NumericValue::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.NumericValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NumericValue::CopyFrom(const NumericValue& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.NumericValue)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NumericValue::IsInitialized() const {
  return true;
}

void NumericValue::Swap(NumericValue* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NumericValue::InternalSwap(NumericValue* other) {
  using std::swap;
  label_.Swap(&other->label_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(color_, other->color_);
  swap(value_, other->value_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NumericValue::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Widget::InitAsDefaultInstance() {
  ::guiMessage::_Widget_default_instance_._instance.get_mutable()->color_ = const_cast< ::guiMessage::Color*>(
      ::guiMessage::Color::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Widget::kColorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Widget::Widget()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Widget.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.Widget)
}
Widget::Widget(const Widget& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_color()) {
    color_ = new ::guiMessage::Color(*from.color_);
  } else {
    color_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:guiMessage.Widget)
}

void Widget::SharedCtor() {
  color_ = NULL;
}

Widget::~Widget() {
  // @@protoc_insertion_point(destructor:guiMessage.Widget)
  SharedDtor();
}

void Widget::SharedDtor() {
  if (this != internal_default_instance()) delete color_;
}

void Widget::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Widget::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Widget& Widget::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_Widget.base);
  return *internal_default_instance();
}


void Widget::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.Widget)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && color_ != NULL) {
    delete color_;
  }
  color_ = NULL;
  _internal_metadata_.Clear();
}

bool Widget::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.Widget)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .guiMessage.Color color = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_color()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.Widget)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.Widget)
  return false;
#undef DO_
}

void Widget::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.Widget)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_color(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.Widget)
}

::google::protobuf::uint8* Widget::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.Widget)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_color(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.Widget)
  return target;
}

size_t Widget::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.Widget)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .guiMessage.Color color = 1;
  if (this->has_color()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *color_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Widget::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.Widget)
  GOOGLE_DCHECK_NE(&from, this);
  const Widget* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Widget>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.Widget)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.Widget)
    MergeFrom(*source);
  }
}

void Widget::MergeFrom(const Widget& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.Widget)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_color()) {
    mutable_color()->::guiMessage::Color::MergeFrom(from.color());
  }
}

void Widget::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.Widget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Widget::CopyFrom(const Widget& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.Widget)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Widget::IsInitialized() const {
  return true;
}

void Widget::Swap(Widget* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Widget::InternalSwap(Widget* other) {
  using std::swap;
  swap(color_, other->color_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Widget::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ContentNode::InitAsDefaultInstance() {
  ::guiMessage::_ContentNode_default_instance_.numericvalue_ = const_cast< ::guiMessage::NumericValue*>(
      ::guiMessage::NumericValue::internal_default_instance());
  ::guiMessage::_ContentNode_default_instance_.widget_ = const_cast< ::guiMessage::Widget*>(
      ::guiMessage::Widget::internal_default_instance());
}
void ContentNode::set_allocated_numericvalue(::guiMessage::NumericValue* numericvalue) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Content();
  if (numericvalue) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      numericvalue = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, numericvalue, submessage_arena);
    }
    set_has_numericvalue();
    Content_.numericvalue_ = numericvalue;
  }
  // @@protoc_insertion_point(field_set_allocated:guiMessage.ContentNode.numericValue)
}
void ContentNode::set_allocated_widget(::guiMessage::Widget* widget) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_Content();
  if (widget) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      widget = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, widget, submessage_arena);
    }
    set_has_widget();
    Content_.widget_ = widget;
  }
  // @@protoc_insertion_point(field_set_allocated:guiMessage.ContentNode.widget)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ContentNode::kLayoutNodeIdFieldNumber;
const int ContentNode::kNumericValueFieldNumber;
const int ContentNode::kWidgetFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ContentNode::ContentNode()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_ContentNode.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.ContentNode)
}
ContentNode::ContentNode(const ContentNode& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  layoutnodeid_ = from.layoutnodeid_;
  clear_has_Content();
  switch (from.Content_case()) {
    case kNumericValue: {
      mutable_numericvalue()->::guiMessage::NumericValue::MergeFrom(from.numericvalue());
      break;
    }
    case kWidget: {
      mutable_widget()->::guiMessage::Widget::MergeFrom(from.widget());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:guiMessage.ContentNode)
}

void ContentNode::SharedCtor() {
  layoutnodeid_ = 0u;
  clear_has_Content();
}

ContentNode::~ContentNode() {
  // @@protoc_insertion_point(destructor:guiMessage.ContentNode)
  SharedDtor();
}

void ContentNode::SharedDtor() {
  if (has_Content()) {
    clear_Content();
  }
}

void ContentNode::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ContentNode::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ContentNode& ContentNode::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_ContentNode.base);
  return *internal_default_instance();
}


void ContentNode::clear_Content() {
// @@protoc_insertion_point(one_of_clear_start:guiMessage.ContentNode)
  switch (Content_case()) {
    case kNumericValue: {
      delete Content_.numericvalue_;
      break;
    }
    case kWidget: {
      delete Content_.widget_;
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = CONTENT_NOT_SET;
}


void ContentNode::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.ContentNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  layoutnodeid_ = 0u;
  clear_Content();
  _internal_metadata_.Clear();
}

bool ContentNode::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.ContentNode)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 layoutNodeId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &layoutnodeid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .guiMessage.NumericValue numericValue = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_numericvalue()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .guiMessage.Widget widget = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_widget()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.ContentNode)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.ContentNode)
  return false;
#undef DO_
}

void ContentNode::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.ContentNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 layoutNodeId = 1;
  if (this->layoutnodeid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->layoutnodeid(), output);
  }

  // .guiMessage.NumericValue numericValue = 2;
  if (has_numericvalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_numericvalue(), output);
  }

  // .guiMessage.Widget widget = 3;
  if (has_widget()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->_internal_widget(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.ContentNode)
}

::google::protobuf::uint8* ContentNode::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.ContentNode)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 layoutNodeId = 1;
  if (this->layoutnodeid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->layoutnodeid(), target);
  }

  // .guiMessage.NumericValue numericValue = 2;
  if (has_numericvalue()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_numericvalue(), deterministic, target);
  }

  // .guiMessage.Widget widget = 3;
  if (has_widget()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->_internal_widget(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.ContentNode)
  return target;
}

size_t ContentNode::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.ContentNode)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // uint32 layoutNodeId = 1;
  if (this->layoutnodeid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->layoutnodeid());
  }

  switch (Content_case()) {
    // .guiMessage.NumericValue numericValue = 2;
    case kNumericValue: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Content_.numericvalue_);
      break;
    }
    // .guiMessage.Widget widget = 3;
    case kWidget: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *Content_.widget_);
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ContentNode::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.ContentNode)
  GOOGLE_DCHECK_NE(&from, this);
  const ContentNode* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ContentNode>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.ContentNode)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.ContentNode)
    MergeFrom(*source);
  }
}

void ContentNode::MergeFrom(const ContentNode& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.ContentNode)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.layoutnodeid() != 0) {
    set_layoutnodeid(from.layoutnodeid());
  }
  switch (from.Content_case()) {
    case kNumericValue: {
      mutable_numericvalue()->::guiMessage::NumericValue::MergeFrom(from.numericvalue());
      break;
    }
    case kWidget: {
      mutable_widget()->::guiMessage::Widget::MergeFrom(from.widget());
      break;
    }
    case CONTENT_NOT_SET: {
      break;
    }
  }
}

void ContentNode::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.ContentNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ContentNode::CopyFrom(const ContentNode& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.ContentNode)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ContentNode::IsInitialized() const {
  return true;
}

void ContentNode::Swap(ContentNode* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ContentNode::InternalSwap(ContentNode* other) {
  using std::swap;
  swap(layoutnodeid_, other->layoutnodeid_);
  swap(Content_, other->Content_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ContentNode::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Gui::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Gui::kLayoutNodesFieldNumber;
const int Gui::kContentNodesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Gui::Gui()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_guiMessage_5ftest_2eproto::scc_info_Gui.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:guiMessage.Gui)
}
Gui::Gui(const Gui& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      layoutnodes_(from.layoutnodes_),
      contentnodes_(from.contentnodes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:guiMessage.Gui)
}

void Gui::SharedCtor() {
}

Gui::~Gui() {
  // @@protoc_insertion_point(destructor:guiMessage.Gui)
  SharedDtor();
}

void Gui::SharedDtor() {
}

void Gui::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Gui::descriptor() {
  ::protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Gui& Gui::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_guiMessage_5ftest_2eproto::scc_info_Gui.base);
  return *internal_default_instance();
}


void Gui::Clear() {
// @@protoc_insertion_point(message_clear_start:guiMessage.Gui)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  layoutnodes_.Clear();
  contentnodes_.Clear();
  _internal_metadata_.Clear();
}

bool Gui::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:guiMessage.Gui)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .guiMessage.LayoutNode layoutNodes = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_layoutnodes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .guiMessage.ContentNode contentNodes = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_contentnodes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:guiMessage.Gui)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:guiMessage.Gui)
  return false;
#undef DO_
}

void Gui::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:guiMessage.Gui)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .guiMessage.LayoutNode layoutNodes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->layoutnodes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->layoutnodes(static_cast<int>(i)),
      output);
  }

  // repeated .guiMessage.ContentNode contentNodes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->contentnodes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->contentnodes(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:guiMessage.Gui)
}

::google::protobuf::uint8* Gui::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:guiMessage.Gui)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .guiMessage.LayoutNode layoutNodes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->layoutnodes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->layoutnodes(static_cast<int>(i)), deterministic, target);
  }

  // repeated .guiMessage.ContentNode contentNodes = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->contentnodes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->contentnodes(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:guiMessage.Gui)
  return target;
}

size_t Gui::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:guiMessage.Gui)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .guiMessage.LayoutNode layoutNodes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->layoutnodes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->layoutnodes(static_cast<int>(i)));
    }
  }

  // repeated .guiMessage.ContentNode contentNodes = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->contentnodes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->contentnodes(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Gui::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:guiMessage.Gui)
  GOOGLE_DCHECK_NE(&from, this);
  const Gui* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Gui>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:guiMessage.Gui)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:guiMessage.Gui)
    MergeFrom(*source);
  }
}

void Gui::MergeFrom(const Gui& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:guiMessage.Gui)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  layoutnodes_.MergeFrom(from.layoutnodes_);
  contentnodes_.MergeFrom(from.contentnodes_);
}

void Gui::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:guiMessage.Gui)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Gui::CopyFrom(const Gui& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:guiMessage.Gui)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Gui::IsInitialized() const {
  return true;
}

void Gui::Swap(Gui* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Gui::InternalSwap(Gui* other) {
  using std::swap;
  CastToBase(&layoutnodes_)->InternalSwap(CastToBase(&other->layoutnodes_));
  CastToBase(&contentnodes_)->InternalSwap(CastToBase(&other->contentnodes_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Gui::GetMetadata() const {
  protobuf_guiMessage_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_guiMessage_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace guiMessage
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::LayoutNode* Arena::CreateMaybeMessage< ::guiMessage::LayoutNode >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::LayoutNode >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::Color* Arena::CreateMaybeMessage< ::guiMessage::Color >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::Color >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::NumericValue* Arena::CreateMaybeMessage< ::guiMessage::NumericValue >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::NumericValue >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::Widget* Arena::CreateMaybeMessage< ::guiMessage::Widget >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::Widget >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::ContentNode* Arena::CreateMaybeMessage< ::guiMessage::ContentNode >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::ContentNode >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::guiMessage::Gui* Arena::CreateMaybeMessage< ::guiMessage::Gui >(Arena* arena) {
  return Arena::CreateInternal< ::guiMessage::Gui >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
