// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MotorValve_test.proto

#ifndef PROTOBUF_INCLUDED_MotorValve_5ftest_2eproto
#define PROTOBUF_INCLUDED_MotorValve_5ftest_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "brewblox_test.pb.h"
#include "nanopb_test.pb.h"
#include "Constraints_test.pb.h"
#include "IoArray_test.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_MotorValve_5ftest_2eproto 

namespace protobuf_MotorValve_5ftest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_MotorValve_5ftest_2eproto
namespace blox_test {
namespace MotorValve {
class Block;
class BlockDefaultTypeInternal;
extern BlockDefaultTypeInternal _Block_default_instance_;
}  // namespace MotorValve
}  // namespace blox_test
namespace google {
namespace protobuf {
template<> ::blox_test::MotorValve::Block* Arena::CreateMaybeMessage<::blox_test::MotorValve::Block>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace blox_test {
namespace MotorValve {

enum ValveState {
  VALVE_UNKNOWN = 0,
  VALVE_OPEN = 1,
  VALVE_CLOSED = 2,
  VALVE_OPENING = 3,
  VALVE_CLOSING = 4,
  VALVE_HALF_OPEN_IDLE = 5,
  VALVE_INIT_IDLE = 6,
  ValveState_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  ValveState_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool ValveState_IsValid(int value);
const ValveState ValveState_MIN = VALVE_UNKNOWN;
const ValveState ValveState_MAX = VALVE_INIT_IDLE;
const int ValveState_ARRAYSIZE = ValveState_MAX + 1;

const ::google::protobuf::EnumDescriptor* ValveState_descriptor();
inline const ::std::string& ValveState_Name(ValveState value) {
  return ::google::protobuf::internal::NameOfEnum(
    ValveState_descriptor(), value);
}
inline bool ValveState_Parse(
    const ::std::string& name, ValveState* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ValveState>(
    ValveState_descriptor(), name, value);
}
// ===================================================================

class Block : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:blox_test.MotorValve.Block) */ {
 public:
  Block();
  virtual ~Block();

  Block(const Block& from);

  inline Block& operator=(const Block& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Block(Block&& from) noexcept
    : Block() {
    *this = ::std::move(from);
  }

  inline Block& operator=(Block&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Block& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Block* internal_default_instance() {
    return reinterpret_cast<const Block*>(
               &_Block_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Block* other);
  friend void swap(Block& a, Block& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Block* New() const final {
    return CreateMaybeMessage<Block>(NULL);
  }

  Block* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Block>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Block& from);
  void MergeFrom(const Block& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Block* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .blox_test.Constraints.DigitalConstraints constrainedBy = 5;
  bool has_constrainedby() const;
  void clear_constrainedby();
  static const int kConstrainedByFieldNumber = 5;
  private:
  const ::blox_test::Constraints::DigitalConstraints& _internal_constrainedby() const;
  public:
  const ::blox_test::Constraints::DigitalConstraints& constrainedby() const;
  ::blox_test::Constraints::DigitalConstraints* release_constrainedby();
  ::blox_test::Constraints::DigitalConstraints* mutable_constrainedby();
  void set_allocated_constrainedby(::blox_test::Constraints::DigitalConstraints* constrainedby);

  // uint32 hwDevice = 1 [(.nanopb) = {
  void clear_hwdevice();
  static const int kHwDeviceFieldNumber = 1;
  ::google::protobuf::uint32 hwdevice() const;
  void set_hwdevice(::google::protobuf::uint32 value);

  // uint32 channel = 2 [(.nanopb) = {
  void clear_channel();
  static const int kChannelFieldNumber = 2;
  ::google::protobuf::uint32 channel() const;
  void set_channel(::google::protobuf::uint32 value);

  // .blox_test.IoArray.DigitalState state = 3 [(.brewblox.field) = {
  void clear_state();
  static const int kStateFieldNumber = 3;
  ::blox_test::IoArray::DigitalState state() const;
  void set_state(::blox_test::IoArray::DigitalState value);

  // .blox_test.MotorValve.ValveState valveState = 6 [(.brewblox.field) = {
  void clear_valvestate();
  static const int kValveStateFieldNumber = 6;
  ::blox_test::MotorValve::ValveState valvestate() const;
  void set_valvestate(::blox_test::MotorValve::ValveState value);

  // .blox_test.IoArray.DigitalState desiredState = 7 [(.brewblox.field) = {
  void clear_desiredstate();
  static const int kDesiredStateFieldNumber = 7;
  ::blox_test::IoArray::DigitalState desiredstate() const;
  void set_desiredstate(::blox_test::IoArray::DigitalState value);

  // uint32 claimedBy = 8 [(.nanopb) = {
  void clear_claimedby();
  static const int kClaimedByFieldNumber = 8;
  ::google::protobuf::uint32 claimedby() const;
  void set_claimedby(::google::protobuf::uint32 value);

  // bool startChannel = 90 [(.nanopb) = {
  void clear_startchannel();
  static const int kStartChannelFieldNumber = 90;
  bool startchannel() const;
  void set_startchannel(bool value);

  // @@protoc_insertion_point(class_scope:blox_test.MotorValve.Block)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::blox_test::Constraints::DigitalConstraints* constrainedby_;
  ::google::protobuf::uint32 hwdevice_;
  ::google::protobuf::uint32 channel_;
  int state_;
  int valvestate_;
  int desiredstate_;
  ::google::protobuf::uint32 claimedby_;
  bool startchannel_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_MotorValve_5ftest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Block

// uint32 hwDevice = 1 [(.nanopb) = {
inline void Block::clear_hwdevice() {
  hwdevice_ = 0u;
}
inline ::google::protobuf::uint32 Block::hwdevice() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.hwDevice)
  return hwdevice_;
}
inline void Block::set_hwdevice(::google::protobuf::uint32 value) {
  
  hwdevice_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.hwDevice)
}

// uint32 channel = 2 [(.nanopb) = {
inline void Block::clear_channel() {
  channel_ = 0u;
}
inline ::google::protobuf::uint32 Block::channel() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.channel)
  return channel_;
}
inline void Block::set_channel(::google::protobuf::uint32 value) {
  
  channel_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.channel)
}

// .blox_test.IoArray.DigitalState state = 3 [(.brewblox.field) = {
inline void Block::clear_state() {
  state_ = 0;
}
inline ::blox_test::IoArray::DigitalState Block::state() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.state)
  return static_cast< ::blox_test::IoArray::DigitalState >(state_);
}
inline void Block::set_state(::blox_test::IoArray::DigitalState value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.state)
}

// .blox_test.Constraints.DigitalConstraints constrainedBy = 5;
inline bool Block::has_constrainedby() const {
  return this != internal_default_instance() && constrainedby_ != NULL;
}
inline const ::blox_test::Constraints::DigitalConstraints& Block::_internal_constrainedby() const {
  return *constrainedby_;
}
inline const ::blox_test::Constraints::DigitalConstraints& Block::constrainedby() const {
  const ::blox_test::Constraints::DigitalConstraints* p = constrainedby_;
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.constrainedBy)
  return p != NULL ? *p : *reinterpret_cast<const ::blox_test::Constraints::DigitalConstraints*>(
      &::blox_test::Constraints::_DigitalConstraints_default_instance_);
}
inline ::blox_test::Constraints::DigitalConstraints* Block::release_constrainedby() {
  // @@protoc_insertion_point(field_release:blox_test.MotorValve.Block.constrainedBy)
  
  ::blox_test::Constraints::DigitalConstraints* temp = constrainedby_;
  constrainedby_ = NULL;
  return temp;
}
inline ::blox_test::Constraints::DigitalConstraints* Block::mutable_constrainedby() {
  
  if (constrainedby_ == NULL) {
    auto* p = CreateMaybeMessage<::blox_test::Constraints::DigitalConstraints>(GetArenaNoVirtual());
    constrainedby_ = p;
  }
  // @@protoc_insertion_point(field_mutable:blox_test.MotorValve.Block.constrainedBy)
  return constrainedby_;
}
inline void Block::set_allocated_constrainedby(::blox_test::Constraints::DigitalConstraints* constrainedby) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(constrainedby_);
  }
  if (constrainedby) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      constrainedby = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, constrainedby, submessage_arena);
    }
    
  } else {
    
  }
  constrainedby_ = constrainedby;
  // @@protoc_insertion_point(field_set_allocated:blox_test.MotorValve.Block.constrainedBy)
}

// .blox_test.MotorValve.ValveState valveState = 6 [(.brewblox.field) = {
inline void Block::clear_valvestate() {
  valvestate_ = 0;
}
inline ::blox_test::MotorValve::ValveState Block::valvestate() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.valveState)
  return static_cast< ::blox_test::MotorValve::ValveState >(valvestate_);
}
inline void Block::set_valvestate(::blox_test::MotorValve::ValveState value) {
  
  valvestate_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.valveState)
}

// .blox_test.IoArray.DigitalState desiredState = 7 [(.brewblox.field) = {
inline void Block::clear_desiredstate() {
  desiredstate_ = 0;
}
inline ::blox_test::IoArray::DigitalState Block::desiredstate() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.desiredState)
  return static_cast< ::blox_test::IoArray::DigitalState >(desiredstate_);
}
inline void Block::set_desiredstate(::blox_test::IoArray::DigitalState value) {
  
  desiredstate_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.desiredState)
}

// uint32 claimedBy = 8 [(.nanopb) = {
inline void Block::clear_claimedby() {
  claimedby_ = 0u;
}
inline ::google::protobuf::uint32 Block::claimedby() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.claimedBy)
  return claimedby_;
}
inline void Block::set_claimedby(::google::protobuf::uint32 value) {
  
  claimedby_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.claimedBy)
}

// bool startChannel = 90 [(.nanopb) = {
inline void Block::clear_startchannel() {
  startchannel_ = false;
}
inline bool Block::startchannel() const {
  // @@protoc_insertion_point(field_get:blox_test.MotorValve.Block.startChannel)
  return startchannel_;
}
inline void Block::set_startchannel(bool value) {
  
  startchannel_ = value;
  // @@protoc_insertion_point(field_set:blox_test.MotorValve.Block.startChannel)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MotorValve
}  // namespace blox_test

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::blox_test::MotorValve::ValveState> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::blox_test::MotorValve::ValveState>() {
  return ::blox_test::MotorValve::ValveState_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_MotorValve_5ftest_2eproto
