#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"

UNCOMMITTED_CHANGES=$(cd "$REPO_ROOT/external_libs/brewblox-proto" && git diff-index HEAD)

if [ -n "$UNCOMMITTED_CHANGES" ]; then
	echo "Uncommitted changes in proto submodule detected!"
	exit 1
fi

UNPUSHED_CHANGES=$(cd "$REPO_ROOT/external_libs/brewblox-proto" && git diff origin/develop)

if [ -n "$UNPUSHED_CHANGES" ]; then
	echo "Unpushed changes in proto submodule detected!"
	exit 1
fi

PROTO_SHA=$(cd "$REPO_ROOT/external_libs/brewblox-proto" && git rev-parse --short=8 HEAD)

if grep -q "$PROTO_SHA" lib/proto/inc/proto/proto_version.h; then
	exit 0
else
	echo "sha in lib/proto/inc/proto/proto_version.h doesn't match proto submodule. Re-run compile-proto.sh"
	exit 1
fi
