#! /usr/bin/env bash
set -euo pipefail
pushd "$(dirname "$0")" > /dev/null

particle usb listen
echo ""
echo "IMPORTANT: answer 'no' when asked to scan for Wifi networks"
echo ""
particle serial wifi
