#!/bin/sh

REPO_ROOT="$(git rev-parse --show-toplevel)"
PROTO_SHA=$(cd "$REPO_ROOT/brewblox/blox/proto" && git rev-parse --short=8 HEAD)
if grep -q "$PROTO_SHA" brewblox/blox/compiled_proto/src/proto_version.h; then
	exit 0
else
  echo "sha in brewblox/blox/compiled_proto/src/proto_version.h doesn't match proto submodule. Re-run compile-proto.sh"
	exit 1
fi
