// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActuatorAnalogMock_test.proto

#ifndef PROTOBUF_INCLUDED_ActuatorAnalogMock_5ftest_2eproto
#define PROTOBUF_INCLUDED_ActuatorAnalogMock_5ftest_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brewblox_test.pb.h"
#include "nanopb_test.pb.h"
#include "AnalogConstraints_test.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ActuatorAnalogMock_5ftest_2eproto 

namespace protobuf_ActuatorAnalogMock_5ftest_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ActuatorAnalogMock_5ftest_2eproto
namespace blox {
class ActuatorAnalogMock;
class ActuatorAnalogMockDefaultTypeInternal;
extern ActuatorAnalogMockDefaultTypeInternal _ActuatorAnalogMock_default_instance_;
}  // namespace blox
namespace google {
namespace protobuf {
template<> ::blox::ActuatorAnalogMock* Arena::CreateMaybeMessage<::blox::ActuatorAnalogMock>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace blox {

// ===================================================================

class ActuatorAnalogMock : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:blox.ActuatorAnalogMock) */ {
 public:
  ActuatorAnalogMock();
  virtual ~ActuatorAnalogMock();

  ActuatorAnalogMock(const ActuatorAnalogMock& from);

  inline ActuatorAnalogMock& operator=(const ActuatorAnalogMock& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ActuatorAnalogMock(ActuatorAnalogMock&& from) noexcept
    : ActuatorAnalogMock() {
    *this = ::std::move(from);
  }

  inline ActuatorAnalogMock& operator=(ActuatorAnalogMock&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ActuatorAnalogMock& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ActuatorAnalogMock* internal_default_instance() {
    return reinterpret_cast<const ActuatorAnalogMock*>(
               &_ActuatorAnalogMock_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ActuatorAnalogMock* other);
  friend void swap(ActuatorAnalogMock& a, ActuatorAnalogMock& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ActuatorAnalogMock* New() const final {
    return CreateMaybeMessage<ActuatorAnalogMock>(NULL);
  }

  ActuatorAnalogMock* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ActuatorAnalogMock>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ActuatorAnalogMock& from);
  void MergeFrom(const ActuatorAnalogMock& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActuatorAnalogMock* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 strippedFields = 99 [(.nanopb_test) = {
  int strippedfields_size() const;
  void clear_strippedfields();
  static const int kStrippedFieldsFieldNumber = 99;
  ::google::protobuf::uint32 strippedfields(int index) const;
  void set_strippedfields(int index, ::google::protobuf::uint32 value);
  void add_strippedfields(::google::protobuf::uint32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      strippedfields() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_strippedfields();

  // .blox.AnalogConstraints constrainedBy = 8;
  bool has_constrainedby() const;
  void clear_constrainedby();
  static const int kConstrainedByFieldNumber = 8;
  private:
  const ::blox::AnalogConstraints& _internal_constrainedby() const;
  public:
  const ::blox::AnalogConstraints& constrainedby() const;
  ::blox::AnalogConstraints* release_constrainedby();
  ::blox::AnalogConstraints* mutable_constrainedby();
  void set_allocated_constrainedby(::blox::AnalogConstraints* constrainedby);

  // sint32 setting = 1 [(.nanopb_test) = {
  void clear_setting();
  static const int kSettingFieldNumber = 1;
  ::google::protobuf::int32 setting() const;
  void set_setting(::google::protobuf::int32 value);

  // sint32 value = 2 [(.nanopb_test) = {
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // sint32 minSetting = 4 [(.nanopb_test) = {
  void clear_minsetting();
  static const int kMinSettingFieldNumber = 4;
  ::google::protobuf::int32 minsetting() const;
  void set_minsetting(::google::protobuf::int32 value);

  // sint32 maxSetting = 5 [(.nanopb_test) = {
  void clear_maxsetting();
  static const int kMaxSettingFieldNumber = 5;
  ::google::protobuf::int32 maxsetting() const;
  void set_maxsetting(::google::protobuf::int32 value);

  // sint32 minValue = 6 [(.nanopb_test) = {
  void clear_minvalue();
  static const int kMinValueFieldNumber = 6;
  ::google::protobuf::int32 minvalue() const;
  void set_minvalue(::google::protobuf::int32 value);

  // sint32 maxValue = 7 [(.nanopb_test) = {
  void clear_maxvalue();
  static const int kMaxValueFieldNumber = 7;
  ::google::protobuf::int32 maxvalue() const;
  void set_maxvalue(::google::protobuf::int32 value);

  // sint32 desiredSetting = 9 [(.nanopb_test) = {
  void clear_desiredsetting();
  static const int kDesiredSettingFieldNumber = 9;
  ::google::protobuf::int32 desiredsetting() const;
  void set_desiredsetting(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:blox.ActuatorAnalogMock)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > strippedfields_;
  mutable int _strippedfields_cached_byte_size_;
  ::blox::AnalogConstraints* constrainedby_;
  ::google::protobuf::int32 setting_;
  ::google::protobuf::int32 value_;
  ::google::protobuf::int32 minsetting_;
  ::google::protobuf::int32 maxsetting_;
  ::google::protobuf::int32 minvalue_;
  ::google::protobuf::int32 maxvalue_;
  ::google::protobuf::int32 desiredsetting_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ActuatorAnalogMock_5ftest_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ActuatorAnalogMock

// sint32 setting = 1 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_setting() {
  setting_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::setting() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.setting)
  return setting_;
}
inline void ActuatorAnalogMock::set_setting(::google::protobuf::int32 value) {
  
  setting_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.setting)
}

// sint32 value = 2 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::value() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.value)
  return value_;
}
inline void ActuatorAnalogMock::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.value)
}

// sint32 minSetting = 4 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_minsetting() {
  minsetting_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::minsetting() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.minSetting)
  return minsetting_;
}
inline void ActuatorAnalogMock::set_minsetting(::google::protobuf::int32 value) {
  
  minsetting_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.minSetting)
}

// sint32 maxSetting = 5 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_maxsetting() {
  maxsetting_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::maxsetting() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.maxSetting)
  return maxsetting_;
}
inline void ActuatorAnalogMock::set_maxsetting(::google::protobuf::int32 value) {
  
  maxsetting_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.maxSetting)
}

// sint32 minValue = 6 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_minvalue() {
  minvalue_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::minvalue() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.minValue)
  return minvalue_;
}
inline void ActuatorAnalogMock::set_minvalue(::google::protobuf::int32 value) {
  
  minvalue_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.minValue)
}

// sint32 maxValue = 7 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_maxvalue() {
  maxvalue_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::maxvalue() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.maxValue)
  return maxvalue_;
}
inline void ActuatorAnalogMock::set_maxvalue(::google::protobuf::int32 value) {
  
  maxvalue_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.maxValue)
}

// .blox.AnalogConstraints constrainedBy = 8;
inline bool ActuatorAnalogMock::has_constrainedby() const {
  return this != internal_default_instance() && constrainedby_ != NULL;
}
inline const ::blox::AnalogConstraints& ActuatorAnalogMock::_internal_constrainedby() const {
  return *constrainedby_;
}
inline const ::blox::AnalogConstraints& ActuatorAnalogMock::constrainedby() const {
  const ::blox::AnalogConstraints* p = constrainedby_;
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.constrainedBy)
  return p != NULL ? *p : *reinterpret_cast<const ::blox::AnalogConstraints*>(
      &::blox::_AnalogConstraints_default_instance_);
}
inline ::blox::AnalogConstraints* ActuatorAnalogMock::release_constrainedby() {
  // @@protoc_insertion_point(field_release:blox.ActuatorAnalogMock.constrainedBy)
  
  ::blox::AnalogConstraints* temp = constrainedby_;
  constrainedby_ = NULL;
  return temp;
}
inline ::blox::AnalogConstraints* ActuatorAnalogMock::mutable_constrainedby() {
  
  if (constrainedby_ == NULL) {
    auto* p = CreateMaybeMessage<::blox::AnalogConstraints>(GetArenaNoVirtual());
    constrainedby_ = p;
  }
  // @@protoc_insertion_point(field_mutable:blox.ActuatorAnalogMock.constrainedBy)
  return constrainedby_;
}
inline void ActuatorAnalogMock::set_allocated_constrainedby(::blox::AnalogConstraints* constrainedby) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(constrainedby_);
  }
  if (constrainedby) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      constrainedby = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, constrainedby, submessage_arena);
    }
    
  } else {
    
  }
  constrainedby_ = constrainedby;
  // @@protoc_insertion_point(field_set_allocated:blox.ActuatorAnalogMock.constrainedBy)
}

// sint32 desiredSetting = 9 [(.nanopb_test) = {
inline void ActuatorAnalogMock::clear_desiredsetting() {
  desiredsetting_ = 0;
}
inline ::google::protobuf::int32 ActuatorAnalogMock::desiredsetting() const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.desiredSetting)
  return desiredsetting_;
}
inline void ActuatorAnalogMock::set_desiredsetting(::google::protobuf::int32 value) {
  
  desiredsetting_ = value;
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.desiredSetting)
}

// repeated uint32 strippedFields = 99 [(.nanopb_test) = {
inline int ActuatorAnalogMock::strippedfields_size() const {
  return strippedfields_.size();
}
inline void ActuatorAnalogMock::clear_strippedfields() {
  strippedfields_.Clear();
}
inline ::google::protobuf::uint32 ActuatorAnalogMock::strippedfields(int index) const {
  // @@protoc_insertion_point(field_get:blox.ActuatorAnalogMock.strippedFields)
  return strippedfields_.Get(index);
}
inline void ActuatorAnalogMock::set_strippedfields(int index, ::google::protobuf::uint32 value) {
  strippedfields_.Set(index, value);
  // @@protoc_insertion_point(field_set:blox.ActuatorAnalogMock.strippedFields)
}
inline void ActuatorAnalogMock::add_strippedfields(::google::protobuf::uint32 value) {
  strippedfields_.Add(value);
  // @@protoc_insertion_point(field_add:blox.ActuatorAnalogMock.strippedFields)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ActuatorAnalogMock::strippedfields() const {
  // @@protoc_insertion_point(field_list:blox.ActuatorAnalogMock.strippedFields)
  return strippedfields_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ActuatorAnalogMock::mutable_strippedfields() {
  // @@protoc_insertion_point(field_mutable_list:blox.ActuatorAnalogMock.strippedFields)
  return &strippedfields_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace blox

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ActuatorAnalogMock_5ftest_2eproto
