// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ActuatorPwm_test.proto

#include "ActuatorPwm_test.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace blox {
constexpr ActuatorPwm::ActuatorPwm(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : strippedfields_()
  , _strippedfields_cached_byte_size_(0)
  , constrainedby_(nullptr)
  , actuatorid_(0u)
  , period_(0u)
  , setting_(0)
  , value_(0)
  , drivenactuatorid_(0u)
  , enabled_(false)
  , desiredsetting_(0){}
struct ActuatorPwmDefaultTypeInternal {
  constexpr ActuatorPwmDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~ActuatorPwmDefaultTypeInternal() {}
  union {
    ActuatorPwm _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT ActuatorPwmDefaultTypeInternal _ActuatorPwm_default_instance_;
}  // namespace blox
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_ActuatorPwm_5ftest_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_ActuatorPwm_5ftest_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_ActuatorPwm_5ftest_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_ActuatorPwm_5ftest_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, actuatorid_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, period_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, setting_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, value_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, constrainedby_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, drivenactuatorid_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, enabled_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, desiredsetting_),
  PROTOBUF_FIELD_OFFSET(::blox::ActuatorPwm, strippedfields_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::blox::ActuatorPwm)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::blox::_ActuatorPwm_default_instance_),
};

const char descriptor_table_protodef_ActuatorPwm_5ftest_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026ActuatorPwm_test.proto\022\004blox\032\023brewblox"
  "_test.proto\032\021nanopb_test.proto\032\034AnalogCo"
  "nstraints_test.proto\"\200\003\n\013ActuatorPwm\022\037\n\n"
  "actuatorId\030\001 \001(\rB\013\212\265\030\002\030\006\222\?\0028\020\022\035\n\006period\030"
  "\003 \001(\rB\r\212\265\030\002\010\003\212\265\030\003\020\350\007\022)\n\007setting\030\004 \001(\021B\030\212"
  "\265\030\0020\001\212\265\030\002(\001\212\265\030\003\020\200 \222\?\0028 \022\'\n\005value\030\005 \001(\021B\030"
  "\212\265\030\0020\001\212\265\030\003\020\200 \222\?\0028 \212\265\030\002(\001\022.\n\rconstrainedB"
  "y\030\006 \001(\0132\027.blox.AnalogConstraints\0221\n\020driv"
  "enActuatorId\030\007 \001(\rB\027\212\265\030\002\030\006\212\265\030\002@\001\222\?\0028\020\212\265\030"
  "\002(\001\022\017\n\007enabled\030\010 \001(\010\022*\n\016desiredSetting\030\t"
  " \001(\021B\022\212\265\030\0020\001\212\265\030\003\020\200 \222\?\0028 \022(\n\016strippedFiel"
  "ds\030c \003(\rB\020\212\265\030\002(\001\222\?\0028\020\222\?\002\020\002:\023\212\265\030\003\030\263\002\212\265\030\002H"
  "\001\212\265\030\002H\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_ActuatorPwm_5ftest_2eproto_deps[3] = {
  &::descriptor_table_AnalogConstraints_5ftest_2eproto,
  &::descriptor_table_brewblox_5ftest_2eproto,
  &::descriptor_table_nanopb_5ftest_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_ActuatorPwm_5ftest_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ActuatorPwm_5ftest_2eproto = {
  false, false, 495, descriptor_table_protodef_ActuatorPwm_5ftest_2eproto, "ActuatorPwm_test.proto", 
  &descriptor_table_ActuatorPwm_5ftest_2eproto_once, descriptor_table_ActuatorPwm_5ftest_2eproto_deps, 3, 1,
  schemas, file_default_instances, TableStruct_ActuatorPwm_5ftest_2eproto::offsets,
  file_level_metadata_ActuatorPwm_5ftest_2eproto, file_level_enum_descriptors_ActuatorPwm_5ftest_2eproto, file_level_service_descriptors_ActuatorPwm_5ftest_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_ActuatorPwm_5ftest_2eproto_getter() {
  return &descriptor_table_ActuatorPwm_5ftest_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_ActuatorPwm_5ftest_2eproto(&descriptor_table_ActuatorPwm_5ftest_2eproto);
namespace blox {

// ===================================================================

class ActuatorPwm::_Internal {
 public:
  static const ::blox::AnalogConstraints& constrainedby(const ActuatorPwm* msg);
};

const ::blox::AnalogConstraints&
ActuatorPwm::_Internal::constrainedby(const ActuatorPwm* msg) {
  return *msg->constrainedby_;
}
void ActuatorPwm::clear_constrainedby() {
  if (GetArenaForAllocation() == nullptr && constrainedby_ != nullptr) {
    delete constrainedby_;
  }
  constrainedby_ = nullptr;
}
ActuatorPwm::ActuatorPwm(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  strippedfields_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:blox.ActuatorPwm)
}
ActuatorPwm::ActuatorPwm(const ActuatorPwm& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      strippedfields_(from.strippedfields_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_constrainedby()) {
    constrainedby_ = new ::blox::AnalogConstraints(*from.constrainedby_);
  } else {
    constrainedby_ = nullptr;
  }
  ::memcpy(&actuatorid_, &from.actuatorid_,
    static_cast<size_t>(reinterpret_cast<char*>(&desiredsetting_) -
    reinterpret_cast<char*>(&actuatorid_)) + sizeof(desiredsetting_));
  // @@protoc_insertion_point(copy_constructor:blox.ActuatorPwm)
}

inline void ActuatorPwm::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&constrainedby_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&desiredsetting_) -
    reinterpret_cast<char*>(&constrainedby_)) + sizeof(desiredsetting_));
}

ActuatorPwm::~ActuatorPwm() {
  // @@protoc_insertion_point(destructor:blox.ActuatorPwm)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void ActuatorPwm::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete constrainedby_;
}

void ActuatorPwm::ArenaDtor(void* object) {
  ActuatorPwm* _this = reinterpret_cast< ActuatorPwm* >(object);
  (void)_this;
}
void ActuatorPwm::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void ActuatorPwm::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ActuatorPwm::Clear() {
// @@protoc_insertion_point(message_clear_start:blox.ActuatorPwm)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  strippedfields_.Clear();
  if (GetArenaForAllocation() == nullptr && constrainedby_ != nullptr) {
    delete constrainedby_;
  }
  constrainedby_ = nullptr;
  ::memset(&actuatorid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&desiredsetting_) -
      reinterpret_cast<char*>(&actuatorid_)) + sizeof(desiredsetting_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ActuatorPwm::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 actuatorId = 1 [(.nanopb_test) = {
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          actuatorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 period = 3 [(.brewblox_test) = {
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          period_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // sint32 setting = 4 [(.nanopb_test) = {
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          setting_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // sint32 value = 5 [(.nanopb_test) = {
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 40)) {
          value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .blox.AnalogConstraints constrainedBy = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          ptr = ctx->ParseMessage(_internal_mutable_constrainedby(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 drivenActuatorId = 7 [(.nanopb_test) = {
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 56)) {
          drivenactuatorid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // bool enabled = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 64)) {
          enabled_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // sint32 desiredSetting = 9 [(.nanopb_test) = {
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 72)) {
          desiredsetting_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarintZigZag32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated uint32 strippedFields = 99 [(.nanopb_test) = {
      case 99:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_strippedfields(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24) {
          _internal_add_strippedfields(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* ActuatorPwm::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:blox.ActuatorPwm)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 actuatorId = 1 [(.nanopb_test) = {
  if (this->_internal_actuatorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_actuatorid(), target);
  }

  // uint32 period = 3 [(.brewblox_test) = {
  if (this->_internal_period() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_period(), target);
  }

  // sint32 setting = 4 [(.nanopb_test) = {
  if (this->_internal_setting() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt32ToArray(4, this->_internal_setting(), target);
  }

  // sint32 value = 5 [(.nanopb_test) = {
  if (this->_internal_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt32ToArray(5, this->_internal_value(), target);
  }

  // .blox.AnalogConstraints constrainedBy = 6;
  if (this->_internal_has_constrainedby()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        6, _Internal::constrainedby(this), target, stream);
  }

  // uint32 drivenActuatorId = 7 [(.nanopb_test) = {
  if (this->_internal_drivenactuatorid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(7, this->_internal_drivenactuatorid(), target);
  }

  // bool enabled = 8;
  if (this->_internal_enabled() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteBoolToArray(8, this->_internal_enabled(), target);
  }

  // sint32 desiredSetting = 9 [(.nanopb_test) = {
  if (this->_internal_desiredsetting() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteSInt32ToArray(9, this->_internal_desiredsetting(), target);
  }

  // repeated uint32 strippedFields = 99 [(.nanopb_test) = {
  {
    int byte_size = _strippedfields_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          99, _internal_strippedfields(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:blox.ActuatorPwm)
  return target;
}

size_t ActuatorPwm::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:blox.ActuatorPwm)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated uint32 strippedFields = 99 [(.nanopb_test) = {
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt32Size(this->strippedfields_);
    if (data_size > 0) {
      total_size += 2 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _strippedfields_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .blox.AnalogConstraints constrainedBy = 6;
  if (this->_internal_has_constrainedby()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *constrainedby_);
  }

  // uint32 actuatorId = 1 [(.nanopb_test) = {
  if (this->_internal_actuatorid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_actuatorid());
  }

  // uint32 period = 3 [(.brewblox_test) = {
  if (this->_internal_period() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_period());
  }

  // sint32 setting = 4 [(.nanopb_test) = {
  if (this->_internal_setting() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt32Size(
        this->_internal_setting());
  }

  // sint32 value = 5 [(.nanopb_test) = {
  if (this->_internal_value() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt32Size(
        this->_internal_value());
  }

  // uint32 drivenActuatorId = 7 [(.nanopb_test) = {
  if (this->_internal_drivenactuatorid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_drivenactuatorid());
  }

  // bool enabled = 8;
  if (this->_internal_enabled() != 0) {
    total_size += 1 + 1;
  }

  // sint32 desiredSetting = 9 [(.nanopb_test) = {
  if (this->_internal_desiredsetting() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SInt32Size(
        this->_internal_desiredsetting());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ActuatorPwm::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ActuatorPwm::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ActuatorPwm::GetClassData() const { return &_class_data_; }

void ActuatorPwm::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<ActuatorPwm *>(to)->MergeFrom(
      static_cast<const ActuatorPwm &>(from));
}


void ActuatorPwm::MergeFrom(const ActuatorPwm& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:blox.ActuatorPwm)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  strippedfields_.MergeFrom(from.strippedfields_);
  if (from._internal_has_constrainedby()) {
    _internal_mutable_constrainedby()->::blox::AnalogConstraints::MergeFrom(from._internal_constrainedby());
  }
  if (from._internal_actuatorid() != 0) {
    _internal_set_actuatorid(from._internal_actuatorid());
  }
  if (from._internal_period() != 0) {
    _internal_set_period(from._internal_period());
  }
  if (from._internal_setting() != 0) {
    _internal_set_setting(from._internal_setting());
  }
  if (from._internal_value() != 0) {
    _internal_set_value(from._internal_value());
  }
  if (from._internal_drivenactuatorid() != 0) {
    _internal_set_drivenactuatorid(from._internal_drivenactuatorid());
  }
  if (from._internal_enabled() != 0) {
    _internal_set_enabled(from._internal_enabled());
  }
  if (from._internal_desiredsetting() != 0) {
    _internal_set_desiredsetting(from._internal_desiredsetting());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ActuatorPwm::CopyFrom(const ActuatorPwm& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:blox.ActuatorPwm)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ActuatorPwm::IsInitialized() const {
  return true;
}

void ActuatorPwm::InternalSwap(ActuatorPwm* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  strippedfields_.InternalSwap(&other->strippedfields_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ActuatorPwm, desiredsetting_)
      + sizeof(ActuatorPwm::desiredsetting_)
      - PROTOBUF_FIELD_OFFSET(ActuatorPwm, constrainedby_)>(
          reinterpret_cast<char*>(&constrainedby_),
          reinterpret_cast<char*>(&other->constrainedby_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ActuatorPwm::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_ActuatorPwm_5ftest_2eproto_getter, &descriptor_table_ActuatorPwm_5ftest_2eproto_once,
      file_level_metadata_ActuatorPwm_5ftest_2eproto[0]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace blox
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::blox::ActuatorPwm* Arena::CreateMaybeMessage< ::blox::ActuatorPwm >(Arena* arena) {
  return Arena::CreateMessageInternal< ::blox::ActuatorPwm >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
