// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OneWireBus_test.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_OneWireBus_5ftest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_OneWireBus_5ftest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "brewblox_test.pb.h"
#include "nanopb_test.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_OneWireBus_5ftest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_OneWireBus_5ftest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_OneWireBus_5ftest_2eproto;
namespace blox {
class OneWireBus;
struct OneWireBusDefaultTypeInternal;
extern OneWireBusDefaultTypeInternal _OneWireBus_default_instance_;
class OneWireBusCommand;
struct OneWireBusCommandDefaultTypeInternal;
extern OneWireBusCommandDefaultTypeInternal _OneWireBusCommand_default_instance_;
}  // namespace blox
PROTOBUF_NAMESPACE_OPEN
template<> ::blox::OneWireBus* Arena::CreateMaybeMessage<::blox::OneWireBus>(Arena*);
template<> ::blox::OneWireBusCommand* Arena::CreateMaybeMessage<::blox::OneWireBusCommand>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace blox {

// ===================================================================

class OneWireBusCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blox.OneWireBusCommand) */ {
 public:
  inline OneWireBusCommand() : OneWireBusCommand(nullptr) {}
  ~OneWireBusCommand() override;
  explicit constexpr OneWireBusCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneWireBusCommand(const OneWireBusCommand& from);
  OneWireBusCommand(OneWireBusCommand&& from) noexcept
    : OneWireBusCommand() {
    *this = ::std::move(from);
  }

  inline OneWireBusCommand& operator=(const OneWireBusCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneWireBusCommand& operator=(OneWireBusCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneWireBusCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneWireBusCommand* internal_default_instance() {
    return reinterpret_cast<const OneWireBusCommand*>(
               &_OneWireBusCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(OneWireBusCommand& a, OneWireBusCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(OneWireBusCommand* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneWireBusCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OneWireBusCommand* New() const final {
    return new OneWireBusCommand();
  }

  OneWireBusCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OneWireBusCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneWireBusCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const OneWireBusCommand& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneWireBusCommand* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blox.OneWireBusCommand";
  }
  protected:
  explicit OneWireBusCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOpcodeFieldNumber = 1,
    kDataFieldNumber = 2,
  };
  // uint32 opcode = 1 [(.nanopb_test) = {
  void clear_opcode();
  ::PROTOBUF_NAMESPACE_ID::uint32 opcode() const;
  void set_opcode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_opcode() const;
  void _internal_set_opcode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 data = 2 [(.nanopb_test) = {
  void clear_data();
  ::PROTOBUF_NAMESPACE_ID::uint32 data() const;
  void set_data(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_data() const;
  void _internal_set_data(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:blox.OneWireBusCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 opcode_;
  ::PROTOBUF_NAMESPACE_ID::uint32 data_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_OneWireBus_5ftest_2eproto;
};
// -------------------------------------------------------------------

class OneWireBus final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blox.OneWireBus) */ {
 public:
  inline OneWireBus() : OneWireBus(nullptr) {}
  ~OneWireBus() override;
  explicit constexpr OneWireBus(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  OneWireBus(const OneWireBus& from);
  OneWireBus(OneWireBus&& from) noexcept
    : OneWireBus() {
    *this = ::std::move(from);
  }

  inline OneWireBus& operator=(const OneWireBus& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneWireBus& operator=(OneWireBus&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const OneWireBus& default_instance() {
    return *internal_default_instance();
  }
  static inline const OneWireBus* internal_default_instance() {
    return reinterpret_cast<const OneWireBus*>(
               &_OneWireBus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(OneWireBus& a, OneWireBus& b) {
    a.Swap(&b);
  }
  inline void Swap(OneWireBus* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneWireBus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OneWireBus* New() const final {
    return new OneWireBus();
  }

  OneWireBus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OneWireBus>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const OneWireBus& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const OneWireBus& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneWireBus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blox.OneWireBus";
  }
  protected:
  explicit OneWireBus(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAddressFieldNumber = 2,
    kCommandFieldNumber = 1,
  };
  // repeated fixed64 address = 2 [(.brewblox_test) = {
  int address_size() const;
  private:
  int _internal_address_size() const;
  public:
  void clear_address();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_address(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      _internal_address() const;
  void _internal_add_address(::PROTOBUF_NAMESPACE_ID::uint64 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      _internal_mutable_address();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint64 address(int index) const;
  void set_address(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_address(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      address() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_address();

  // .blox.OneWireBusCommand command = 1;
  bool has_command() const;
  private:
  bool _internal_has_command() const;
  public:
  void clear_command();
  const ::blox::OneWireBusCommand& command() const;
  PROTOBUF_MUST_USE_RESULT ::blox::OneWireBusCommand* release_command();
  ::blox::OneWireBusCommand* mutable_command();
  void set_allocated_command(::blox::OneWireBusCommand* command);
  private:
  const ::blox::OneWireBusCommand& _internal_command() const;
  ::blox::OneWireBusCommand* _internal_mutable_command();
  public:
  void unsafe_arena_set_allocated_command(
      ::blox::OneWireBusCommand* command);
  ::blox::OneWireBusCommand* unsafe_arena_release_command();

  // @@protoc_insertion_point(class_scope:blox.OneWireBus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > address_;
  ::blox::OneWireBusCommand* command_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_OneWireBus_5ftest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// OneWireBusCommand

// uint32 opcode = 1 [(.nanopb_test) = {
inline void OneWireBusCommand::clear_opcode() {
  opcode_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OneWireBusCommand::_internal_opcode() const {
  return opcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OneWireBusCommand::opcode() const {
  // @@protoc_insertion_point(field_get:blox.OneWireBusCommand.opcode)
  return _internal_opcode();
}
inline void OneWireBusCommand::_internal_set_opcode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  opcode_ = value;
}
inline void OneWireBusCommand::set_opcode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_opcode(value);
  // @@protoc_insertion_point(field_set:blox.OneWireBusCommand.opcode)
}

// uint32 data = 2 [(.nanopb_test) = {
inline void OneWireBusCommand::clear_data() {
  data_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OneWireBusCommand::_internal_data() const {
  return data_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 OneWireBusCommand::data() const {
  // @@protoc_insertion_point(field_get:blox.OneWireBusCommand.data)
  return _internal_data();
}
inline void OneWireBusCommand::_internal_set_data(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  data_ = value;
}
inline void OneWireBusCommand::set_data(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:blox.OneWireBusCommand.data)
}

// -------------------------------------------------------------------

// OneWireBus

// .blox.OneWireBusCommand command = 1;
inline bool OneWireBus::_internal_has_command() const {
  return this != internal_default_instance() && command_ != nullptr;
}
inline bool OneWireBus::has_command() const {
  return _internal_has_command();
}
inline void OneWireBus::clear_command() {
  if (GetArenaForAllocation() == nullptr && command_ != nullptr) {
    delete command_;
  }
  command_ = nullptr;
}
inline const ::blox::OneWireBusCommand& OneWireBus::_internal_command() const {
  const ::blox::OneWireBusCommand* p = command_;
  return p != nullptr ? *p : reinterpret_cast<const ::blox::OneWireBusCommand&>(
      ::blox::_OneWireBusCommand_default_instance_);
}
inline const ::blox::OneWireBusCommand& OneWireBus::command() const {
  // @@protoc_insertion_point(field_get:blox.OneWireBus.command)
  return _internal_command();
}
inline void OneWireBus::unsafe_arena_set_allocated_command(
    ::blox::OneWireBusCommand* command) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(command_);
  }
  command_ = command;
  if (command) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:blox.OneWireBus.command)
}
inline ::blox::OneWireBusCommand* OneWireBus::release_command() {
  
  ::blox::OneWireBusCommand* temp = command_;
  command_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::blox::OneWireBusCommand* OneWireBus::unsafe_arena_release_command() {
  // @@protoc_insertion_point(field_release:blox.OneWireBus.command)
  
  ::blox::OneWireBusCommand* temp = command_;
  command_ = nullptr;
  return temp;
}
inline ::blox::OneWireBusCommand* OneWireBus::_internal_mutable_command() {
  
  if (command_ == nullptr) {
    auto* p = CreateMaybeMessage<::blox::OneWireBusCommand>(GetArenaForAllocation());
    command_ = p;
  }
  return command_;
}
inline ::blox::OneWireBusCommand* OneWireBus::mutable_command() {
  ::blox::OneWireBusCommand* _msg = _internal_mutable_command();
  // @@protoc_insertion_point(field_mutable:blox.OneWireBus.command)
  return _msg;
}
inline void OneWireBus::set_allocated_command(::blox::OneWireBusCommand* command) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete command_;
  }
  if (command) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper<::blox::OneWireBusCommand>::GetOwningArena(command);
    if (message_arena != submessage_arena) {
      command = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, command, submessage_arena);
    }
    
  } else {
    
  }
  command_ = command;
  // @@protoc_insertion_point(field_set_allocated:blox.OneWireBus.command)
}

// repeated fixed64 address = 2 [(.brewblox_test) = {
inline int OneWireBus::_internal_address_size() const {
  return address_.size();
}
inline int OneWireBus::address_size() const {
  return _internal_address_size();
}
inline void OneWireBus::clear_address() {
  address_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 OneWireBus::_internal_address(int index) const {
  return address_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 OneWireBus::address(int index) const {
  // @@protoc_insertion_point(field_get:blox.OneWireBus.address)
  return _internal_address(index);
}
inline void OneWireBus::set_address(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  address_.Set(index, value);
  // @@protoc_insertion_point(field_set:blox.OneWireBus.address)
}
inline void OneWireBus::_internal_add_address(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  address_.Add(value);
}
inline void OneWireBus::add_address(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_add_address(value);
  // @@protoc_insertion_point(field_add:blox.OneWireBus.address)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
OneWireBus::_internal_address() const {
  return address_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
OneWireBus::address() const {
  // @@protoc_insertion_point(field_list:blox.OneWireBus.address)
  return _internal_address();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
OneWireBus::_internal_mutable_address() {
  return &address_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
OneWireBus::mutable_address() {
  // @@protoc_insertion_point(field_mutable_list:blox.OneWireBus.address)
  return _internal_mutable_address();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace blox

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_OneWireBus_5ftest_2eproto
