// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetpointSensorPair_test.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SetpointSensorPair_5ftest_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SetpointSensorPair_5ftest_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017003 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "brewblox_test.pb.h"
#include "nanopb_test.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SetpointSensorPair_5ftest_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SetpointSensorPair_5ftest_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SetpointSensorPair_5ftest_2eproto;
namespace blox {
class SetpointSensorPair;
struct SetpointSensorPairDefaultTypeInternal;
extern SetpointSensorPairDefaultTypeInternal _SetpointSensorPair_default_instance_;
}  // namespace blox
PROTOBUF_NAMESPACE_OPEN
template<> ::blox::SetpointSensorPair* Arena::CreateMaybeMessage<::blox::SetpointSensorPair>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace blox {

enum FilterChoice : int {
  FILTER_NONE = 0,
  FILTER_15s = 1,
  FILTER_45s = 2,
  FILTER_90s = 3,
  FILTER_3m = 4,
  FILTER_10m = 5,
  FILTER_30m = 6,
  FilterChoice_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  FilterChoice_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool FilterChoice_IsValid(int value);
constexpr FilterChoice FilterChoice_MIN = FILTER_NONE;
constexpr FilterChoice FilterChoice_MAX = FILTER_30m;
constexpr int FilterChoice_ARRAYSIZE = FilterChoice_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* FilterChoice_descriptor();
template<typename T>
inline const std::string& FilterChoice_Name(T enum_t_value) {
  static_assert(::std::is_same<T, FilterChoice>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function FilterChoice_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    FilterChoice_descriptor(), enum_t_value);
}
inline bool FilterChoice_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, FilterChoice* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<FilterChoice>(
    FilterChoice_descriptor(), name, value);
}
// ===================================================================

class SetpointSensorPair final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:blox.SetpointSensorPair) */ {
 public:
  inline SetpointSensorPair() : SetpointSensorPair(nullptr) {}
  ~SetpointSensorPair() override;
  explicit constexpr SetpointSensorPair(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetpointSensorPair(const SetpointSensorPair& from);
  SetpointSensorPair(SetpointSensorPair&& from) noexcept
    : SetpointSensorPair() {
    *this = ::std::move(from);
  }

  inline SetpointSensorPair& operator=(const SetpointSensorPair& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetpointSensorPair& operator=(SetpointSensorPair&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetpointSensorPair& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetpointSensorPair* internal_default_instance() {
    return reinterpret_cast<const SetpointSensorPair*>(
               &_SetpointSensorPair_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SetpointSensorPair& a, SetpointSensorPair& b) {
    a.Swap(&b);
  }
  inline void Swap(SetpointSensorPair* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetpointSensorPair* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SetpointSensorPair* New() const final {
    return new SetpointSensorPair();
  }

  SetpointSensorPair* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SetpointSensorPair>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetpointSensorPair& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SetpointSensorPair& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to, const ::PROTOBUF_NAMESPACE_ID::Message&from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetpointSensorPair* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "blox.SetpointSensorPair";
  }
  protected:
  explicit SetpointSensorPair(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStrippedFieldsFieldNumber = 99,
    kSensorIdFieldNumber = 2,
    kSettingFieldNumber = 5,
    kValueFieldNumber = 6,
    kStoredSettingFieldNumber = 8,
    kFilterFieldNumber = 9,
    kSettingEnabledFieldNumber = 7,
    kResetFilterFieldNumber = 12,
    kFilterThresholdFieldNumber = 10,
    kValueUnfilteredFieldNumber = 11,
  };
  // repeated uint32 strippedFields = 99 [(.nanopb_test) = {
  int strippedfields_size() const;
  private:
  int _internal_strippedfields_size() const;
  public:
  void clear_strippedfields();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_strippedfields(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_strippedfields() const;
  void _internal_add_strippedfields(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_strippedfields();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 strippedfields(int index) const;
  void set_strippedfields(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_strippedfields(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      strippedfields() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_strippedfields();

  // uint32 sensorId = 2 [(.nanopb_test) = {
  void clear_sensorid();
  ::PROTOBUF_NAMESPACE_ID::uint32 sensorid() const;
  void set_sensorid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_sensorid() const;
  void _internal_set_sensorid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // sint32 setting = 5 [(.nanopb_test) = {
  void clear_setting();
  ::PROTOBUF_NAMESPACE_ID::int32 setting() const;
  void set_setting(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_setting() const;
  void _internal_set_setting(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // sint32 value = 6 [(.nanopb_test) = {
  void clear_value();
  ::PROTOBUF_NAMESPACE_ID::int32 value() const;
  void set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_value() const;
  void _internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // sint32 storedSetting = 8 [(.nanopb_test) = {
  void clear_storedsetting();
  ::PROTOBUF_NAMESPACE_ID::int32 storedsetting() const;
  void set_storedsetting(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_storedsetting() const;
  void _internal_set_storedsetting(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .blox.FilterChoice filter = 9;
  void clear_filter();
  ::blox::FilterChoice filter() const;
  void set_filter(::blox::FilterChoice value);
  private:
  ::blox::FilterChoice _internal_filter() const;
  void _internal_set_filter(::blox::FilterChoice value);
  public:

  // bool settingEnabled = 7;
  void clear_settingenabled();
  bool settingenabled() const;
  void set_settingenabled(bool value);
  private:
  bool _internal_settingenabled() const;
  void _internal_set_settingenabled(bool value);
  public:

  // bool resetFilter = 12;
  void clear_resetfilter();
  bool resetfilter() const;
  void set_resetfilter(bool value);
  private:
  bool _internal_resetfilter() const;
  void _internal_set_resetfilter(bool value);
  public:

  // sint32 filterThreshold = 10 [(.nanopb_test) = {
  void clear_filterthreshold();
  ::PROTOBUF_NAMESPACE_ID::int32 filterthreshold() const;
  void set_filterthreshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_filterthreshold() const;
  void _internal_set_filterthreshold(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // sint32 valueUnfiltered = 11 [(.nanopb_test) = {
  void clear_valueunfiltered();
  ::PROTOBUF_NAMESPACE_ID::int32 valueunfiltered() const;
  void set_valueunfiltered(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_valueunfiltered() const;
  void _internal_set_valueunfiltered(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:blox.SetpointSensorPair)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > strippedfields_;
  mutable std::atomic<int> _strippedfields_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 sensorid_;
  ::PROTOBUF_NAMESPACE_ID::int32 setting_;
  ::PROTOBUF_NAMESPACE_ID::int32 value_;
  ::PROTOBUF_NAMESPACE_ID::int32 storedsetting_;
  int filter_;
  bool settingenabled_;
  bool resetfilter_;
  ::PROTOBUF_NAMESPACE_ID::int32 filterthreshold_;
  ::PROTOBUF_NAMESPACE_ID::int32 valueunfiltered_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SetpointSensorPair_5ftest_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SetpointSensorPair

// uint32 sensorId = 2 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_sensorid() {
  sensorid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SetpointSensorPair::_internal_sensorid() const {
  return sensorid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SetpointSensorPair::sensorid() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.sensorId)
  return _internal_sensorid();
}
inline void SetpointSensorPair::_internal_set_sensorid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  sensorid_ = value;
}
inline void SetpointSensorPair::set_sensorid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_sensorid(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.sensorId)
}

// sint32 setting = 5 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_setting() {
  setting_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::_internal_setting() const {
  return setting_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::setting() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.setting)
  return _internal_setting();
}
inline void SetpointSensorPair::_internal_set_setting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  setting_ = value;
}
inline void SetpointSensorPair::set_setting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_setting(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.setting)
}

// sint32 value = 6 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_value() {
  value_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::_internal_value() const {
  return value_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::value() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.value)
  return _internal_value();
}
inline void SetpointSensorPair::_internal_set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  value_ = value;
}
inline void SetpointSensorPair::set_value(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_value(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.value)
}

// bool settingEnabled = 7;
inline void SetpointSensorPair::clear_settingenabled() {
  settingenabled_ = false;
}
inline bool SetpointSensorPair::_internal_settingenabled() const {
  return settingenabled_;
}
inline bool SetpointSensorPair::settingenabled() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.settingEnabled)
  return _internal_settingenabled();
}
inline void SetpointSensorPair::_internal_set_settingenabled(bool value) {
  
  settingenabled_ = value;
}
inline void SetpointSensorPair::set_settingenabled(bool value) {
  _internal_set_settingenabled(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.settingEnabled)
}

// sint32 storedSetting = 8 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_storedsetting() {
  storedsetting_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::_internal_storedsetting() const {
  return storedsetting_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::storedsetting() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.storedSetting)
  return _internal_storedsetting();
}
inline void SetpointSensorPair::_internal_set_storedsetting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  storedsetting_ = value;
}
inline void SetpointSensorPair::set_storedsetting(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_storedsetting(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.storedSetting)
}

// .blox.FilterChoice filter = 9;
inline void SetpointSensorPair::clear_filter() {
  filter_ = 0;
}
inline ::blox::FilterChoice SetpointSensorPair::_internal_filter() const {
  return static_cast< ::blox::FilterChoice >(filter_);
}
inline ::blox::FilterChoice SetpointSensorPair::filter() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.filter)
  return _internal_filter();
}
inline void SetpointSensorPair::_internal_set_filter(::blox::FilterChoice value) {
  
  filter_ = value;
}
inline void SetpointSensorPair::set_filter(::blox::FilterChoice value) {
  _internal_set_filter(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.filter)
}

// sint32 filterThreshold = 10 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_filterthreshold() {
  filterthreshold_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::_internal_filterthreshold() const {
  return filterthreshold_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::filterthreshold() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.filterThreshold)
  return _internal_filterthreshold();
}
inline void SetpointSensorPair::_internal_set_filterthreshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  filterthreshold_ = value;
}
inline void SetpointSensorPair::set_filterthreshold(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_filterthreshold(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.filterThreshold)
}

// sint32 valueUnfiltered = 11 [(.nanopb_test) = {
inline void SetpointSensorPair::clear_valueunfiltered() {
  valueunfiltered_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::_internal_valueunfiltered() const {
  return valueunfiltered_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SetpointSensorPair::valueunfiltered() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.valueUnfiltered)
  return _internal_valueunfiltered();
}
inline void SetpointSensorPair::_internal_set_valueunfiltered(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  valueunfiltered_ = value;
}
inline void SetpointSensorPair::set_valueunfiltered(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_valueunfiltered(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.valueUnfiltered)
}

// bool resetFilter = 12;
inline void SetpointSensorPair::clear_resetfilter() {
  resetfilter_ = false;
}
inline bool SetpointSensorPair::_internal_resetfilter() const {
  return resetfilter_;
}
inline bool SetpointSensorPair::resetfilter() const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.resetFilter)
  return _internal_resetfilter();
}
inline void SetpointSensorPair::_internal_set_resetfilter(bool value) {
  
  resetfilter_ = value;
}
inline void SetpointSensorPair::set_resetfilter(bool value) {
  _internal_set_resetfilter(value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.resetFilter)
}

// repeated uint32 strippedFields = 99 [(.nanopb_test) = {
inline int SetpointSensorPair::_internal_strippedfields_size() const {
  return strippedfields_.size();
}
inline int SetpointSensorPair::strippedfields_size() const {
  return _internal_strippedfields_size();
}
inline void SetpointSensorPair::clear_strippedfields() {
  strippedfields_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SetpointSensorPair::_internal_strippedfields(int index) const {
  return strippedfields_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SetpointSensorPair::strippedfields(int index) const {
  // @@protoc_insertion_point(field_get:blox.SetpointSensorPair.strippedFields)
  return _internal_strippedfields(index);
}
inline void SetpointSensorPair::set_strippedfields(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  strippedfields_.Set(index, value);
  // @@protoc_insertion_point(field_set:blox.SetpointSensorPair.strippedFields)
}
inline void SetpointSensorPair::_internal_add_strippedfields(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  strippedfields_.Add(value);
}
inline void SetpointSensorPair::add_strippedfields(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_strippedfields(value);
  // @@protoc_insertion_point(field_add:blox.SetpointSensorPair.strippedFields)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
SetpointSensorPair::_internal_strippedfields() const {
  return strippedfields_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
SetpointSensorPair::strippedfields() const {
  // @@protoc_insertion_point(field_list:blox.SetpointSensorPair.strippedFields)
  return _internal_strippedfields();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
SetpointSensorPair::_internal_mutable_strippedfields() {
  return &strippedfields_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
SetpointSensorPair::mutable_strippedfields() {
  // @@protoc_insertion_point(field_mutable_list:blox.SetpointSensorPair.strippedFields)
  return _internal_mutable_strippedfields();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace blox

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::blox::FilterChoice> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::blox::FilterChoice>() {
  return ::blox::FilterChoice_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SetpointSensorPair_5ftest_2eproto
