// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TouchSettings_test.proto

#include "TouchSettings_test.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace blox {
namespace TouchSettings {
class BlockDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Block>
      _instance;
} _Block_default_instance_;
}  // namespace TouchSettings
}  // namespace blox
namespace protobuf_TouchSettings_5ftest_2eproto {
static void InitDefaultsBlock() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::blox::TouchSettings::_Block_default_instance_;
    new (ptr) ::blox::TouchSettings::Block();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::blox::TouchSettings::Block::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Block =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBlock}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Block.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, calibrated_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, xoffset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, yoffset_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, xbitsperpixelx16_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::blox::TouchSettings::Block, ybitsperpixelx16_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::blox::TouchSettings::Block)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::blox::TouchSettings::_Block_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "TouchSettings_test.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030TouchSettings_test.proto\022\022blox.TouchSe"
      "ttings\032\023brewblox_test.proto\032\021nanopb_test"
      ".proto\"\266\001\n\005Block\0222\n\ncalibrated\030\001 \001(\0162\036.b"
      "lox.TouchSettings.Calibrated\022\026\n\007xOffset\030"
      "\002 \001(\005B\005\222\?\0028\020\022\026\n\007yOffset\030\003 \001(\005B\005\222\?\0028\020\022\037\n\020"
      "xBitsPerPixelX16\030\004 \001(\rB\005\222\?\0028\020\022\037\n\020yBitsPe"
      "rPixelX16\030\005 \001(\rB\005\222\?\0028\020:\007\212\265\030\003\030\271\002*G\n\nCalib"
      "rated\022\021\n\rCALIBRATED_NO\020\000\022\022\n\016CALIBRATED_Y"
      "ES\020\001\022\022\n\016CALIBRATED_NEW\020\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 352);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "TouchSettings_test.proto", &protobuf_RegisterTypes);
  ::protobuf_brewblox_5ftest_2eproto::AddDescriptors();
  ::protobuf_nanopb_5ftest_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_TouchSettings_5ftest_2eproto
namespace blox {
namespace TouchSettings {
const ::google::protobuf::EnumDescriptor* Calibrated_descriptor() {
  protobuf_TouchSettings_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_TouchSettings_5ftest_2eproto::file_level_enum_descriptors[0];
}
bool Calibrated_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Block::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Block::kCalibratedFieldNumber;
const int Block::kXOffsetFieldNumber;
const int Block::kYOffsetFieldNumber;
const int Block::kXBitsPerPixelX16FieldNumber;
const int Block::kYBitsPerPixelX16FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Block::Block()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_TouchSettings_5ftest_2eproto::scc_info_Block.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:blox.TouchSettings.Block)
}
Block::Block(const Block& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&calibrated_, &from.calibrated_,
    static_cast<size_t>(reinterpret_cast<char*>(&ybitsperpixelx16_) -
    reinterpret_cast<char*>(&calibrated_)) + sizeof(ybitsperpixelx16_));
  // @@protoc_insertion_point(copy_constructor:blox.TouchSettings.Block)
}

void Block::SharedCtor() {
  ::memset(&calibrated_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ybitsperpixelx16_) -
      reinterpret_cast<char*>(&calibrated_)) + sizeof(ybitsperpixelx16_));
}

Block::~Block() {
  // @@protoc_insertion_point(destructor:blox.TouchSettings.Block)
  SharedDtor();
}

void Block::SharedDtor() {
}

void Block::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Block::descriptor() {
  ::protobuf_TouchSettings_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_TouchSettings_5ftest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Block& Block::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_TouchSettings_5ftest_2eproto::scc_info_Block.base);
  return *internal_default_instance();
}


void Block::Clear() {
// @@protoc_insertion_point(message_clear_start:blox.TouchSettings.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&calibrated_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ybitsperpixelx16_) -
      reinterpret_cast<char*>(&calibrated_)) + sizeof(ybitsperpixelx16_));
  _internal_metadata_.Clear();
}

bool Block::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:blox.TouchSettings.Block)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .blox.TouchSettings.Calibrated calibrated = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_calibrated(static_cast< ::blox::TouchSettings::Calibrated >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 xOffset = 2 [(.nanopb_test) = {
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &xoffset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 yOffset = 3 [(.nanopb_test) = {
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &yoffset_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 xBitsPerPixelX16 = 4 [(.nanopb_test) = {
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &xbitsperpixelx16_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 yBitsPerPixelX16 = 5 [(.nanopb_test) = {
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &ybitsperpixelx16_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:blox.TouchSettings.Block)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:blox.TouchSettings.Block)
  return false;
#undef DO_
}

void Block::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:blox.TouchSettings.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .blox.TouchSettings.Calibrated calibrated = 1;
  if (this->calibrated() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->calibrated(), output);
  }

  // int32 xOffset = 2 [(.nanopb_test) = {
  if (this->xoffset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->xoffset(), output);
  }

  // int32 yOffset = 3 [(.nanopb_test) = {
  if (this->yoffset() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->yoffset(), output);
  }

  // uint32 xBitsPerPixelX16 = 4 [(.nanopb_test) = {
  if (this->xbitsperpixelx16() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->xbitsperpixelx16(), output);
  }

  // uint32 yBitsPerPixelX16 = 5 [(.nanopb_test) = {
  if (this->ybitsperpixelx16() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->ybitsperpixelx16(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:blox.TouchSettings.Block)
}

::google::protobuf::uint8* Block::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:blox.TouchSettings.Block)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .blox.TouchSettings.Calibrated calibrated = 1;
  if (this->calibrated() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->calibrated(), target);
  }

  // int32 xOffset = 2 [(.nanopb_test) = {
  if (this->xoffset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->xoffset(), target);
  }

  // int32 yOffset = 3 [(.nanopb_test) = {
  if (this->yoffset() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->yoffset(), target);
  }

  // uint32 xBitsPerPixelX16 = 4 [(.nanopb_test) = {
  if (this->xbitsperpixelx16() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->xbitsperpixelx16(), target);
  }

  // uint32 yBitsPerPixelX16 = 5 [(.nanopb_test) = {
  if (this->ybitsperpixelx16() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->ybitsperpixelx16(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:blox.TouchSettings.Block)
  return target;
}

size_t Block::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:blox.TouchSettings.Block)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .blox.TouchSettings.Calibrated calibrated = 1;
  if (this->calibrated() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->calibrated());
  }

  // int32 xOffset = 2 [(.nanopb_test) = {
  if (this->xoffset() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->xoffset());
  }

  // int32 yOffset = 3 [(.nanopb_test) = {
  if (this->yoffset() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->yoffset());
  }

  // uint32 xBitsPerPixelX16 = 4 [(.nanopb_test) = {
  if (this->xbitsperpixelx16() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->xbitsperpixelx16());
  }

  // uint32 yBitsPerPixelX16 = 5 [(.nanopb_test) = {
  if (this->ybitsperpixelx16() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->ybitsperpixelx16());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Block::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:blox.TouchSettings.Block)
  GOOGLE_DCHECK_NE(&from, this);
  const Block* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Block>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:blox.TouchSettings.Block)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:blox.TouchSettings.Block)
    MergeFrom(*source);
  }
}

void Block::MergeFrom(const Block& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:blox.TouchSettings.Block)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.calibrated() != 0) {
    set_calibrated(from.calibrated());
  }
  if (from.xoffset() != 0) {
    set_xoffset(from.xoffset());
  }
  if (from.yoffset() != 0) {
    set_yoffset(from.yoffset());
  }
  if (from.xbitsperpixelx16() != 0) {
    set_xbitsperpixelx16(from.xbitsperpixelx16());
  }
  if (from.ybitsperpixelx16() != 0) {
    set_ybitsperpixelx16(from.ybitsperpixelx16());
  }
}

void Block::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:blox.TouchSettings.Block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Block::CopyFrom(const Block& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:blox.TouchSettings.Block)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Block::IsInitialized() const {
  return true;
}

void Block::Swap(Block* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Block::InternalSwap(Block* other) {
  using std::swap;
  swap(calibrated_, other->calibrated_);
  swap(xoffset_, other->xoffset_);
  swap(yoffset_, other->yoffset_);
  swap(xbitsperpixelx16_, other->xbitsperpixelx16_);
  swap(ybitsperpixelx16_, other->ybitsperpixelx16_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Block::GetMetadata() const {
  protobuf_TouchSettings_5ftest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_TouchSettings_5ftest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace TouchSettings
}  // namespace blox
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::blox::TouchSettings::Block* Arena::CreateMaybeMessage< ::blox::TouchSettings::Block >(Arena* arena) {
  return Arena::CreateInternal< ::blox::TouchSettings::Block >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
